# array 인덱싱 
 
## 기본 인덱싱

In [3]:
import numpy as np

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5]

5

In [7]:
arr[5:8]

array([5, 6, 7])

In [8]:
arr[5:8] = 12

In [9]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [11]:
arr[5:8] = [5,6,7]

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2차원 array 

In [13]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
               [13,14,15,16]])

In [14]:
#2행의 전체값 가져오기
arr2[2, :]

array([ 9, 10, 11, 12])

In [15]:
#1행~2행의 전체값 가져오기
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#전체 행을 가져오되, 마지막 열 값만을 가져와라
arr2[:,3]  # 마지막 열 표현은 -1도 가능

array([ 4,  8, 12, 16])

In [17]:
# 3행의 2열값만 가져와라
arr2[3,2]

15

In [18]:
#0~1행까지 1~2열까지의 값만 가져와라
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [19]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 불리언 인덱싱

In [38]:
names = np.array(['Charles','Hyunsuk', 'Hayoung', 'Charles', 'Hayoung', 'Hyunsuk', 'Hyunsuk'])
data = np.random.randn(7,4)

In [39]:
names

array(['Charles', 'Hyunsuk', 'Hayoung', 'Charles', 'Hayoung', 'Hyunsuk',
       'Hyunsuk'],
      dtype='<U7')

In [40]:
data

array([[-1.1450498 , -1.29602029,  0.79355211,  0.21673769],
       [ 0.44493931, -0.18731171, -2.18341882, -0.01474921],
       [ 0.69806282,  2.00481395,  0.81754564,  0.20269519],
       [ 0.50226557,  1.2405164 , -2.3026314 ,  1.01998482],
       [ 0.34620612, -0.26852386, -0.43656405, -0.42451597],
       [-0.04031698,  1.82584632,  1.0519667 , -0.80585493],
       [ 1.38898791, -1.04026844, -0.00574073,  1.92443812]])

In [41]:
# Charles 값만 확인하기
names == 'Charles'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [42]:
#Charles의 마스크를 이용하여 다른 array를 인덱싱하기
data[names == 'Charles', :]

array([[-1.1450498 , -1.29602029,  0.79355211,  0.21673769],
       [ 0.50226557,  1.2405164 , -2.3026314 ,  1.01998482]])

In [43]:
data[names == 'Hyunsuk', :]

array([[ 0.44493931, -0.18731171, -2.18341882, -0.01474921],
       [-0.04031698,  1.82584632,  1.0519667 , -0.80585493],
       [ 1.38898791, -1.04026844, -0.00574073,  1.92443812]])

In [44]:
#Charles 또는 Hyunsuk의 마스크를 이용하여 array 인덱싱하기
data[(names == 'Charles') | (names == 'Hyunsuk'),:]

array([[-1.1450498 , -1.29602029,  0.79355211,  0.21673769],
       [ 0.44493931, -0.18731171, -2.18341882, -0.01474921],
       [ 0.50226557,  1.2405164 , -2.3026314 ,  1.01998482],
       [-0.04031698,  1.82584632,  1.0519667 , -0.80585493],
       [ 1.38898791, -1.04026844, -0.00574073,  1.92443812]])

In [45]:
# 조건부 마스크
data[:, 3] < 0

array([False,  True, False, False,  True,  True, False], dtype=bool)

In [49]:
data[data[:,3] < 0, :] = 0

In [50]:
data

array([[-1.1450498 , -1.29602029,  0.79355211,  0.21673769],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.69806282,  2.00481395,  0.81754564,  0.20269519],
       [ 0.50226557,  1.2405164 , -2.3026314 ,  1.01998482],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.38898791, -1.04026844, -0.00574073,  1.92443812]])