# numpy ndarray 이해하기
 
numpy는 특히 벡터 및 행렬 연산에 있어 편의성을 제공하는 라이브러리로, 여러분들이 추후 많이 사용하게 될 pandas와 matplotlib의 기반이 되는 라이브러리라고 할 수 있음.


In [1]:
import numpy as np

## 1차원 array 

In [2]:
data = [6, 7.5, 8, 0, 1]

In [4]:
arr1 = np.array(data)

In [5]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
arr1.shape

(5,)

In [8]:
arr = np.array([2,3,4])

In [9]:
arr

array([2, 3, 4])

## 2차원 array

In [10]:
data2 = [[1,2,3,4], 
         [5,6,7,8]]

In [11]:
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.shape

(2, 4)

## zeros(), ones(), arange() 함수 기능

In [14]:
# 0으로 된 array를 만든다.
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
# 1로 된 array를 만든다.
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
# 연속된 수로 array를 만든다.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 데이터 타입

**numpy에서 사용 가능한 데이터형(dtype) 정리**
 
**- int8, int16, int32, int64** : 부호가 있는 [8, 16, 32, 64]비트 정수 

**- uint8, uint16, uint32, uint64** : 부호가 없는 [8, 16, 32, 64]비트 정수 

**- float16, float32, float64, float128** :[16, 32, 64, 128]비트 실수 

**- complex64, complex128, complex256** : [64, 128, 256]비트 복소수 

**- bool** : 불리언 (True 또는 False) 

**- object **: Python 오브젝트 형 

**- string_** : 문자열 

**- unicode_ **: 유니코드 문자열 
 

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [22]:
# 데이터 타입 직접 지정하기
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [20]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [21]:
arr.dtype

dtype('int64')

In [23]:
# 기존의 타입을 변경하기 astype()
float_arr = arr.astype(np.float64)


In [24]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [25]:
float_arr.dtype

dtype('float64')

## array 관련 연산
 
두 array 간에는 더하기, 빼기, 곱하기, 나누기 등의 연산을 수행할 수 있습니다. '+', '-', '*', '/' 등과 같이 여러분이 일반 숫자에 대해 사용하는 연산자를 사용하면 됨.
 
이 떄, 이러한 더하기, 빼기, 곱하기, 나누기 등의 연산은 두 array 상의 동일한 위치의 성분끼리 이루어지게 됩니다. 그러므로, 당연히 두 array의 모양이 같아야 계산이 가능함.

In [26]:
 arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [27]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [28]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [29]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [35]:
# 연산 (+) 2차원에서 같은 위치의 성분끼리 연산이 된다. (모든 연산이 같음)
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [39]:
# 각 성분에 일반 숫자를 적용하여 연산하기
arr1 * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [37]:
arr1 ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [38]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])