In [2]:
import numpy as np
import pandas as pd

In [4]:
data = np.loadtxt('data/movielens/ratings.dat', delimiter = '::', dtype=np.int64)

In [4]:
# 5행까지 확인해보기
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [5]:
data.shape

(1000209, 4)

# 전체 평균 평점 계산하기

In [5]:
#데이터 컬럼 내용
#user_id :: item :: rating :: timestamp

In [6]:
mean_rating_total = data[:, 2].mean()

In [7]:
mean_rating_total

3.581564453029317

# 각 사용자 별 평균 평점 계산하기

In [8]:
#user_id에 대해 unique값만 먼저 뽑기
user_ids = np.unique(data[:,0])

In [9]:
user_ids[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [10]:
user_ids.shape

(6040,)

In [11]:
#빈 리스트 생성
mean_rating_by_user_list = []

for user_id in user_ids:
    data_for_user = data[data[:,0] == user_id, :]  
    mean_rating_for_user = data_for_user[:, 2].mean()   
    mean_rating_by_user_list.append([user_id, mean_rating_for_user]) 

In [12]:
data_for_user[:10]

array([[     6040,       573,         4, 956704056],
       [     6040,       589,         4, 956704996],
       [     6040,         1,         3, 957717358],
       [     6040,      2068,         4, 997453982],
       [     6040,       592,         2, 956716016],
       [     6040,       593,         5, 956703954],
       [     6040,      3016,         2, 956716157],
       [     6040,      3017,         1, 956716519],
       [     6040,      2070,         4, 956715676],
       [     6040,      1419,         3, 956704056]], dtype=int64)

In [13]:
mean_rating_by_user_list[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [14]:
mean_rating_by_user_list_array = np.array(mean_rating_by_user_list, dtype=np.float64)

In [15]:
mean_rating_by_user_list_array.shape

(6040, 2)

# 파일에 writing하기

In [47]:
np.savetxt("mean_rating_by_user.csv", mean_rating_by_user_list_array, fmt="%.3f", delimiter=',')